# -*- coding: utf-8 -*-
"""crime

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lZHsCvvLDnLUvNAI5I7Kgqb13I74tacY
"""

# example.py
def get_values():
    # Your logic to generate values
    return [1, 2, 3, 4, 5]

if __name__ == "__main__":
    values = get_values()
    print(values)